name: myapp
description: 'My Cool Dart App'
version: 1.0.0
publish_to: none

dependencies:
  angular: ^4.0.0
  angular_router: ^1.0.2
  angular_forms: ^1.0.0
  http: ^0.11.0
  stream_transform: ^0.0.9
  intl: ^0.15.1
  ng_bootstrap: 0.8.5+1

dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1
  transform_sass: ^0.3.1

transformers:
- transform_sass
- angular:
    entry_points: web/index.dart
- dart_to_js_script_rewriter